name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test-build:
    name: Test and building
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.6

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbers

      - name: Use Prime Numbers
        run: /primes.sh -d prime-numbers

      - name: Install dependencies
        run: pnpm install

      - name: Building
        run: pnpm build
        env:
          DATABASE_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: "random"
          NEXTAUTH_URL: "http://localhost:3000"
          GITHUB_CLIENT_ID: "123"
          GITHUB_CLIENT_SECRET: "1234"
          GOOGLE_CLIENT_ID: "12345"
          GOOGLE_CLIENT_SECRET: "123456"
          FACEBOOK_CLIENT_ID: "1234567"
          FACEBOOK_CLIENT_SECRET: "12345678"

      - name: lintrc
        run: pnpm lint
        env:
          DATABASE_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: "random"
          NEXTAUTH_URL: "http://localhost:3000"
          GITHUB_CLIENT_ID: "123"
          GITHUB_CLIENT_SECRET: "1234"
          GOOGLE_CLIENT_ID: "12345"
          GOOGLE_CLIENT_SECRET: "123456"
          FACEBOOK_CLIENT_ID: "1234567"
          FACEBOOK_CLIENT_SECRET: "12345678"

      - name: Type-checking
        run: pnpm type-check

