name: CI

on:
  push:
    branches: ["development"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test-build:
    name: Test and building
    runs-on: ubuntu-latest

    steps:
      - name: Linting
        run: pnpm lint
